create table if not exists users (
  username text not null default ''::text,
  password text not null,
  constraint users_pkey primary key (username),
  constraint users_username_key unique (username),
  constraint users_password_check check (length(trim(both from password)) > 1),
  constraint users_username_check check (length(trim(both from username)) > 1)
);

create table if not exists submissions (
  id bigint generated by default as identity primary key,
  username text not null,
  task_id text not null,
  selected_image_id text not null,
  label text not null check (label in ('shape', 'color', 'texture')),
  explanation text,
  canvas_json jsonb not null,
  composite_png_base64 text not null,
  created_at timestamptz not null default now(),
  unique (username, task_id)
);

create table if not exists ratings (
  id bigint generated by default as identity primary key,
  username text not null,
  task_id text not null,
  winner_source text not null check (winner_source in ('self', 'peer', 'ai')),
  winner_submission_id text,
  option_payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (username, task_id)
);
