create table if not exists public.users (
  username text not null default ''::text,
  password text not null,
  constraint users_pkey primary key (username),
  constraint users_username_key unique (username),
  constraint users_password_check check (length(trim(both from password)) > 1),
  constraint users_username_check check (length(trim(both from username)) > 1)
);

create table if not exists public.submissions (
  id bigint generated by default as identity primary key,
  username text not null,
  dataset_id text not null,
  task_id text not null,
  selected_image_id text not null,
  labels jsonb not null check (
    jsonb_typeof(labels) = 'array'
    and jsonb_array_length(labels) > 0
  ),
  explanation text,
  canvas_json jsonb not null,
  annotation_layers jsonb,
  composite_png_base64 text not null,
  created_at timestamptz not null default now(),
  unique (username, dataset_id, task_id)
);

create table if not exists public.ratings (
  id bigint generated by default as identity primary key,
  username text not null,
  dataset_id text not null,
  task_id text not null,
  winner_source text not null check (winner_source in ('self', 'peer', 'ai')),
  winner_submission_id text,
  option_payload jsonb not null,
  created_at timestamptz not null default now(),
  unique (username, dataset_id, task_id)
);

create index if not exists submissions_username_idx on public.submissions (username);
create index if not exists submissions_dataset_id_idx on public.submissions (dataset_id);
create index if not exists submissions_task_id_idx on public.submissions (task_id);
create index if not exists ratings_username_idx on public.ratings (username);
create index if not exists ratings_dataset_id_idx on public.ratings (dataset_id);
