create table if not exists public.images (
  dataset_id text not null,
  image_id text not null,
  path text not null,
  hash_kwargs jsonb,
  image_info jsonb not null check (jsonb_typeof(image_info) = 'object'),
  image_group jsonb not null check (
    jsonb_typeof(image_group) = 'array'
    and jsonb_array_length(image_group) > 0
  ),
  created_at timestamptz not null default now(),
  constraint images_pkey primary key (dataset_id, image_id)
);

create table if not exists public.selection_challenges (
  dataset_id text not null,
  challenge_id text not null,
  created_at timestamptz not null default now(),
  constraint selection_challenges_pkey primary key (dataset_id, challenge_id)
);

create table if not exists public.selection_tasks (
  id bigint generated by default as identity primary key,
  dataset_id text not null,
  challenge_id text not null,
  task_index integer not null check (task_index >= 0),
  images jsonb not null check (
    jsonb_typeof(images) = 'array'
    and jsonb_array_length(images) > 0
  ),
  difficulty double precision not null default 0.5 check (
    difficulty >= 0.0 and difficulty <= 1.0
  ),
  created_at timestamptz not null default now(),
  unique (dataset_id, challenge_id, task_index)
);

create table if not exists public.selection_choices (
  id bigint generated by default as identity primary key,
  dataset_id text not null,
  challenge_id text not null,
  task_index integer not null check (task_index >= 0),
  images jsonb not null check (
    jsonb_typeof(images) = 'array'
    and jsonb_array_length(images) > 0
  ),
  username text not null,
  user_kind text not null check (user_kind in ('ai', 'human')),
  choice_index integer not null check (choice_index >= 0),
  explanation text,
  annotations jsonb not null default '[]'::jsonb check (
    jsonb_typeof(annotations) = 'array'
  ),
  artifacts jsonb not null default '{}'::jsonb check (
    jsonb_typeof(artifacts) = 'object'
  ),
  created_at timestamptz not null default now(),
  unique (dataset_id, challenge_id, task_index, username)
);

create table if not exists public.rating_tasks (
  id bigint generated by default as identity primary key,
  dataset_id text not null,
  challenge_id text not null,
  task_index integer not null check (task_index >= 0),
  choices jsonb not null check (
    jsonb_typeof(choices) = 'array'
    and jsonb_array_length(choices) > 0
  ),
  created_at timestamptz not null default now()
);

create table if not exists public.rating_evals (
  id bigint generated by default as identity primary key,
  dataset_id text not null,
  challenge_id text not null,
  task_index integer not null check (task_index >= 0),
  username text not null,
  choices jsonb not null check (
    jsonb_typeof(choices) = 'array'
    and jsonb_array_length(choices) > 0
  ),
  most_convincing jsonb not null check (
    jsonb_typeof(most_convincing) = 'object'
  ),
  most_likely_ai jsonb check (
    most_likely_ai is null or jsonb_typeof(most_likely_ai) = 'object'
  ),
  artifacts jsonb not null default '{}'::jsonb check (
    jsonb_typeof(artifacts) = 'object'
  ),
  created_at timestamptz not null default now(),
  unique (dataset_id, challenge_id, task_index, username)
);

create index if not exists images_dataset_id_idx on public.images (dataset_id);
create index if not exists selection_tasks_dataset_challenge_idx
  on public.selection_tasks (dataset_id, challenge_id);
create index if not exists selection_choices_username_idx
  on public.selection_choices (username);
create index if not exists selection_choices_dataset_challenge_idx
  on public.selection_choices (dataset_id, challenge_id, task_index);
create index if not exists rating_evals_username_idx on public.rating_evals (username);
create index if not exists rating_evals_dataset_challenge_idx
  on public.rating_evals (dataset_id, challenge_id, task_index);
